(defvar root-dir (file-name-directory load-file-name))
(defvar config-dir (concat root-dir "config/"))
(defvar save-dir (concat root-dir "savefile/"))
(setq custom-file (concat config-dir "custom.el"))
(add-to-list 'load-path config-dir)
(unless (file-exists-p save-dir)
  (make-directory save-dir))
(when (eq system-type 'darwin)
  (require 'osx))
(require 'packages)
(require 'gui)
(require 'editor)
(require 'bindings)
(require 'external)
(require 'defuns)
(set-frame-height (selected-frame) 40)
(setenv "PATH" (shell-command-to-string "echo $PATH"))

