(require 'yasnippet)
(yas/global-mode 1)
(require 'smart-tab)
(require 'paredit)
(require 'yaml-mode)
(global-smart-tab-mode 1)
(setq nrepl-popup-stacktraces nil)
(add-hook 'clojure-mode-hook 'rainbow-delimiters-mode)
(add-hook 'clojure-mode-hook 'paredit-mode)
(provide 'external)
